# Generated by Django 4.1 on 2022-09-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocr_image",
            name="file",
            field=models.FileField(upload_to="static/files/"),
        ),
        migrations.AlterField(
            model_name="ocr_image",
            name="image",
            field=models.ImageField(upload_to="static/images/"),
        ),
    ]
